apiVersion: v1
kind: ResourceQuota
metadata:
  name: example
  namespace: produccion
spec:
  hard:
    requests.cpu: '4'
    requests.memory: 4Gi
---
kind: Project
apiVersion: project.openshift.io/v1
metadata:
  name: produccion
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: mariadb-config
  namespace: produccion
data:
  MYSQL_DATABASE: mariadb
---
kind: Secret
apiVersion: v1
metadata:
  name: mariadb-secret
  namespace: produccion
data:
  MYSQL_PASSWORD: bWFyaWFkYg==
  MYSQL_USER: bWFyaWFkYg==
  MYSQL_ROOT_PASSWORD: bWFyaWFkYg==

type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deployment
  namespace: produccion
spec:
  selector:
    matchLabels:
      app: mariadb
  replicas: 1
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb
          env:
            # Define the environment variable
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mariadb-config
                  key: MYSQL_DATABASE
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: MYSQL_PASSWORD
          resources:
            requests:
              memory: "2Gi"
              cpu: "2000m"
          ports:
            - containerPort: 3306